---
title: "AMSI"
author: "Gyu Hwan Park"
date: "30 December 2020"
output: html_document
---

# Project Description

This page documents my progress for the research project **'Variaitonal Inference for Bayesian Nonnegative Matrix Factorization'**. This research project is carried out under the AMSI Vacation Scholarship Program, supervised by Dr. Heejung Shim at the University of Melbourne.

# Outline

* [Research Proposal](assets/VI_proposal.pdf)


# Derivations

* [Laplace Approximation Variational Inference (LAVI)](assets/LAVI_BP-NMF.pdf) - Detailed derivation of the variational factors' updates for BP-NMF (one sparsity matrix) by [Liang et al (2013)](https://www.semanticscholar.org/paper/Beta-Process-Sparse-Nonnegative-Matrix-for-Music-Liang-Hoffman/9ca3a99a33d3275837488e7558cb93bb387ea9cf).

* [Doubly Structured Stochastic Variational Inference (DSSVI) for BP-NMF](assets/DSSVI.pdf) - Extension of [Hoffman and Liang (2014)](https://arxiv.org/abs/1411.1804), where an additional sparsity matrix has been added to enforce sparsity in the first factored matrix as well.

* [Gibbs Sampling version of DSSVI BP-NMF](assets/gibbs_DSSVI.pdf)

* [Doubly sparse LAVI](assets/doubly_sparse_LAVI.pdf) - Derivation of variational factors' updates for doubly sparse BP-NMF. An extension of LAVI for BP-NMF.

# Implementation / Simulations

* [Python implementation of DSSVI algorithm](assets/dssvi_fn.py) - Based on the implementation by [Liang](https://github.com/dawenl/bp_nmf/tree/master/code/ssmf).
* [Simulation 1: non-overlapping clusters in X](assets/01_19_sim_check_real.pdf).
* [DSSVI and SSVI Comparison 1](assets/dssvi_ssvi_both sparse_sameK.html) - Both Sparse Matrices & same K across runs.
* [DSSVI and SSVI Comparison 2](assets/dssvi_ssvi_one sparse_sameK.html) - One Sparse Matrix & same K across runs.
* [DSSVI and SSVI Comparison 3](assets/dssvi_ssvi_both sparse_diffK.html) - Both Sparse Matrices & different K across runs.
* [DSSVI and SSVI Comparison 4](assets/dssvi_ssvi_one sparse_diffK.html) - One Sparse Matrix & different K across runs.
* Visit my [github repository](https://github.com/rbghks0126/DS-NMF-with-SSVI) for final implementation, report (including derivations) and powerpoint slides.

# Final report
* [AMSI report](assets/final_report.pdf)
* [AMSI connect presentation](assets/amsi_connect_presentation.pdf)


# Paper Summaries

## VI NMF

* [Variational Inference: A Review for Statisticians](vi_review_summary.html) - Introduction to Variational Inference (CAVI and SVI).


## Exponential Family

* Coming soon